src/Entity/Materieltype.php
<?php

namespace App\Entity;

use App\Repository\MaterieltypeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=MaterieltypeRepository::class)
 */
class Materieltype
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $marque;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $modele;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $categorie;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $photo;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $document;

    /**
     * @ORM\OneToMany(targetEntity=Materiel::class, mappedBy="materieltype")
     */
    private $materiels;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $photo_titre;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $photo_description;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $document_titre;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $document_description;

    public function __construct()
    {
        $this->materiels = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getMarque(): ?string
    {
        return $this->marque;
    }

    public function setMarque(string $marque): self
    {
        $this->marque = $marque;

        return $this;
    }

    public function getModele(): ?string
    {
        return $this->modele;
    }

    public function setModele(string $modele): self
    {
        $this->modele = $modele;

        return $this;
    }

    public function getCategorie(): ?string
    {
        return $this->categorie;
    }

    public function setCategorie(string $categorie): self
    {
        $this->categorie = $categorie;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getPhoto(): ?string
    {
        return $this->photo;
    }

    public function setPhoto(?string $photo): self
    {
        $this->photo = $photo;

        return $this;
    }

    public function getDocument(): ?string
    {
        return $this->document;
    }

    public function setDocument(?string $document): self
    {
        $this->document = $document;

        return $this;
    }

    /**
     * @return Collection|Materiel[]
     */
    public function getMateriels(): Collection
    {
        return $this->materiels;
    }

    public function addMateriel(Materiel $materiel): self
    {
        if (!$this->materiels->contains($materiel)) {
            $this->materiels[] = $materiel;
            $materiel->setMaterieltype($this);
        }

        return $this;
    }

    public function removeMateriel(Materiel $materiel): self
    {
        if ($this->materiels->removeElement($materiel)) {
            // set the owning side to null (unless already changed)
            if ($materiel->getMaterieltype() === $this) {
                $materiel->setMaterieltype(null);
            }
        }

        return $this;
    }

    public function getPhotoTitre(): ?string
    {
        return $this->photo_titre;
    }

    public function setPhotoTitre(string $photo_titre): self
    {
        $this->photo_titre = $photo_titre;

        return $this;
    }

    public function getPhotoDescription(): ?string
    {
        return $this->photo_description;
    }

    public function setPhotoDescription(?string $photo_description): self
    {
        $this->photo_description = $photo_description;

        return $this;
    }

    public function getDocumentTitre(): ?string
    {
        return $this->document_titre;
    }

    public function setDocumentTitre(?string $document_titre): self
    {
        $this->document_titre = $document_titre;

        return $this;
    }

    public function getDocumentDescription(): ?string
    {
        return $this->document_description;
    }

    public function setDocumentDescription(?string $document_description): self
    {
        $this->document_description = $document_description;

        return $this;
    }
}

src/Form/MaterieltypeType.php
<?php

namespace App\Form;

use App\Entity\Materieltype;
use phpDocumentor\Reflection\Types\Null_;
use PHPUnit\TextUI\XmlConfiguration\File;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class MaterieltypeType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('marque', TextType::class, [
                'attr' => [
                    'placeholder' => "Marque",
                    'autocomplete' => 'off',
                ],

            ])
            ->add('modele', TextType::class, [
                'attr' => [
                    'placehoolder' => 'Modèle'
                ]
            ])
            ->add('categorie', TextType::class, ['attr' => [
                'placeholder' => "Catégorie",
                'autocomplete' => 'off',
            ]])
            ->add('description', TextareaType::class, [
                'attr' => [
                    'placeholder' => "Description",
                    'rows' => '8'
                ],

                "required" => false
            ])
            ->add('photo_titre', TextType::class, [
                'attr' => [
                    'placeholder' => "Titre photo"
                ],
                "required" => false,
                'label' => 'Titre',
            ])
            ->add('photo_description', TextareaType::class, [
                'attr' => [
                    'placeholder' => "Description photo",
                    'rows' => '8'
                ],
                "required" => false,
                'label' => 'Description',
            ])
            ->add('photo', FileType::class, [
                'required' => false,
                'data_class' => Null,
            ])
            ->add('document_titre', TextType::class, [
                'attr' => [
                    'placeholder' => "Titre document",
                ],
                'label' => 'Titre',
                "required" => false
            ])
            ->add('document_description', TextareaType::class, [
                'attr' => [
                    'placeholder' => "Description document",
                    'rows' => '8'
                ],
                'label' => 'Description',
                "required" => false
            ])
            ->add('document', FileType::class, [
                'required' => false,
                'data_class' => Null,
                'label' => 'Document'
            ])
            ->add('enregistrer', SubmitType::class, [
                'attr' => [
                    'class' => 'btn btn-sm btn-success'
                ],
                'label' => 'Mettre à jour'
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Materieltype::class,
        ]);
    }
}

src/Controller/MaterieltypeController.php
<?php

namespace App\Controller;

use App\Entity\Materieltype;
use App\Form\MaterieltypeType;
use App\Services\CheckFormFileHelper;

use App\Repository\MaterieltypeRepository;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\Form\FileUploadError;
use Symfony\Component\Filesystem\Filesystem;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;


#[Route('/materieltype')]
/**
 * @IsGranted("ROLE_MANAGER")
 */
class MaterieltypeController extends AbstractController
{
    #[Route('/', name: 'materieltype_index', methods: ['GET'])]
    public function index(PaginatorInterface $paginatorInterface, Request $request,  MaterieltypeRepository $materieltypeRepository): Response
    {
        $materielstype = $paginatorInterface->paginate($materieltypeRepository->findAll(), $request->query->getInt('page', 1), 10);
        return $this->render('materieltype/index.html.twig', [
            'materieltypes' => $materielstype,
        ]);
    }

    #[Route('/new', name: 'materieltype_new', methods: ['GET', 'POST'])]
    public function new(Request $request, CheckFormFileHelper $checkFormFileHelper): Response
    {
        $materieltype = new Materieltype();
        $form = $this->createForm(MaterieltypeType::class, $materieltype);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            //traitement fichier par injection d'un service
            $materieltype->setDocument($checkFormFileHelper->checkFile($form['document'], 'doc_service'));
            $materieltype->setPhoto($checkFormFileHelper->checkFile($form['photo'], 'photo_service'));

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($materieltype);
            $entityManager->flush();

            return $this->redirectToRoute('materieltype_show', ['id' => $materieltype->getId()], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('materieltype/new.html.twig', [
            'materieltype' => $materieltype,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'materieltype_show', methods: ['GET'])]
    public function show(Materieltype $materieltype): Response
    {
        return $this->render('materieltype/show.html.twig', [
            'materieltype' => $materieltype,
        ]);
    }

    #[Route('/{id}/edit', name: 'materieltype_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Materieltype $materieltype, CheckFormFileHelper $checkFormFileHelper): Response
    {
        $fileDoc = $this->getParameter('UPLOAD_DIR') . $materieltype->getDocument();
        $filePhoto = $this->getParameter(('UPLOAD_DIR')) . $materieltype->getPhoto();

        $form = $this->createForm(MaterieltypeType::class, $materieltype);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            if (!is_null($form->get('photo')->getData())) :
                $materieltype->setPhoto(
                    $checkFormFileHelper->updateFile(
                        $filePhoto,
                        $form['photo'],
                        'photo'
                    )
                );
            else :
                $materieltype->setPhoto(basename($filePhoto));
            endif;
            if (!is_null($form->get('document')->getData())) :
                $materieltype->setDocument(
                    $checkFormFileHelper->updateFile(
                        $fileDoc,
                        $form['document'],
                        'doc'
                    )
                );
            else :
                $materieltype->setDocument(basename($fileDoc));
            endif;






            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('materieltype_show', ['id' => $materieltype->getId()], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('materieltype/edit.html.twig', [
            'materieltype' => $materieltype,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'materieltype_delete', methods: ['POST'])]
    public function delete(Request $request, Materieltype $materieltype, CheckFormFileHelper $checkFormFileHelper): Response
    {

        if ($this->isCsrfTokenValid('delete' . $materieltype->getId(), $request->request->get('_token'))) {

            $checkFormFileHelper->deleteFile($materieltype->getDocument());
            $checkFormFileHelper->deleteFile($materieltype->getPhoto());

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($materieltype);
            $entityManager->flush();
        }

        return $this->redirectToRoute('materieltype_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/materieltype/_delete_form.html.twig
<form class="d-inline" method="post" action="{{ path('materieltype_delete', {'id': materieltype.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ materieltype.id) }}">
    <button class="btn btn-sm btn-danger">Supprimer</button>
</form>

templates/materieltype/_form.html.twig
{% if form is defined %}
	{{ form_errors(form) }}
	{{form_start(form)}}
	{{ form_row(form._token) }}
{% endif %}
{% block  stylesheets %}
<style>
#resultat_marque, #resultat_categorie{
	background-color:white;
	position:absolute;
	top:2.5rem;
	width:100%;

	border: solid 1px grey;
	
	z-index:-15;
}
#resultat_marque li, #resultat_categorie li{
	padding-left:5.5rem;
}
.retour_marque:hover, .retour_categorie:hover{
	cursor: pointer;
	background-color:#d8dbdf;
}

</style>

{% endblock %}


<div class="card  " style="border-bottom:none">
	<div class="alert-primary card-header h5 mb-3">
		<b>
			{% if titre is defined %}
				{{titre}}
			{% endif %}
		</b>
	</div>
	<div class="card-body row justify-content-around ">
		<div class="col-md-5 px-0">
			<div class="input-group mb-3">
				<span class="input-group-text" id="basic-addon1">Marque</span>
				{% if form is defined %}
					{{ form_widget(form.marque) }}
					<span class="input-group-text" id="list_marque">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-list" viewBox="0 0 16 16">
                                <path fill-rule="evenodd" d="M2.5 12a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5z"></path>
                            </svg>
                        </span>
				{% else %}
					<input type="text" autocomplete="off" class="form-control" value="{{materieltype.marque}}" aria-label="Username" aria-describedby="basic-addon1">
				{% endif %}
				<div id="resultat_marque"></div>
			</div>
			<div class="input-group mb-3">
				<span class="input-group-text" id="basic-addon1">Catégorie</span>
				{% if form is defined %}
					{{form_widget(form.categorie)}}
					<span class="input-group-text" id="list_categorie">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-list" viewBox="0 0 16 16">
                                <path fill-rule="evenodd" d="M2.5 12a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5z"></path>
                            </svg>
                        </span>
				{% else %}
					<input type="text" class="form-control" value="{{materieltype.categorie}}" aria-label="Username" aria-describedby="basic-addon1">
				{% endif %}
				<div id="resultat_categorie"></div>
			</div>
			<div class="input-group mb-3">
				<span class="input-group-text" id="basic-addon1">Modèle</span>
				{% if form is defined %}
					{{ form_widget(form.modele,{'attr':{'placeholder':'Modèle'}}) }}
					
				{% else %}
					<input type="text" class="form-control" value="{{materieltype.modele}}" aria-label="Username" aria-describedby="basic-addon1">
				{% endif %}
			</div>

			<div class="card">
				<span class="card-header text-start">Description</span>
				{% if form is defined %}
					{{form_widget(form.description)}}
				{% else %}
					<textarea rows="7" class="form-control" aria-label="Username" aria-describedby="basic-addon1">{{materieltype.description}}</textarea>
				{% endif %}

			</div>

		</div>
		<div class="card col-md-3 px-0">
			<h5 class="card-header">Photo</h5>
			<div class="card-body">
				{% if form is defined %}
				<p>{{form_row(form.photo_titre)}}</p>
				<p>{{form_row(form.photo_description)}}</p>
				{% if materieltype.photo != '' %}

						<a href="/upload/{{materieltype.photo}}" target="_blank">
							<img src="/upload/{{materieltype.photo}}" width="100%" alt=""></a>
					{% endif %}
					<p>{{form_row(form.photo)}}</p>
				{% else %}
					<h5 class="card-title">{{materieltype.photoTitre}}</h5>


					<p class="card-text">{{materieltype.photoDescription}}</p>
					{% if materieltype.photo != '' %}

						<a href="/upload/{{materieltype.photo}}" target="_blank">
							<img src="/upload/{{materieltype.photo}}" width="100%" alt=""></a>
					{% endif %}

				{% endif %}

			</div>
			
		</div>
		<div class="card col-md-3 px-0">
			<h5 class="card-header">Document</h5>
			<div class="card-body">
				{% if form is defined %}
				<p>{{form_row(form.document_titre)}}</p>
				<p>{{form_row(form.document_description)}}</p>
					<p>{{form_row(form.document)}}</p>
					
				{% else %}
					<h5 class="card-title">{{materieltype.documentTitre}}</h5>
					<p class="card-text">{{materieltype.documentDescription}}</p>
					{% if materieltype.document != '' and materieltype.document !='upload' %}

					<button id="document" type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal" data-href="{{materieltype.document}}">
					{{materieltype.documentTitre}}.pdf</button>
					{% endif%}
					{% endif %}
					


				</div>
			</div>


		</div>


		<div class="card-footer d-flex justify-content-end mt-5 mx-4" style="padding: 0.5rem ">
			
			<div>
				{% if form is defined %}
					{{form_widget(form.enregistrer,{'label': enregistrer_label|default('Enregistrer')})}}
				{% else %}
					{% if materieltype.id is defined %}

						<a href="{{url('materieltype_edit',{'id':materieltype.id})}}" class="btn btn-sm btn-primary">Editer</a>
					{% endif %}
				{% endif %}
				{% if form is defined %}
					{{form_end(form)}}
				{% endif %}
				{% if materieltype.id is defined and materieltype.id!='' %}
					{{ include('materieltype/_delete_form.html.twig') }}
				{% endif %}

			</div>

		</div>
	</div>
</div>
<!-- Button trigger modal -->


<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-xl modal-dialog-scrollable">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">{{materieltype.documentTitre}}</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
      <object  id="object" style="height:65vh" width="100%"  data="">
    </object>
	  
	  </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fermer</button>
        
      </div>
    </div>
  </div>
</div>

{% block javascript %}
	<script src={{ asset('js/materielType.js') }}></script>

{% endblock %}

templates/materieltype/_nav.html.twig
<div class="col-md-11 d-flex justify-content-between mx-auto my-3">
	<div class="w-50">
		<h3>{% if titre %} {{titre}} {% endif%}</h3>
	</div>
	<div class="d-flex justify-content-end w-50">
		<a href="{{url('materieltype_index')}}" class="btn btn-sm btn-info mx-1">Liste</a>
		<a href="{{url('materieltype_new')}}" class="btn btn-sm btn-info mx-1">Ajouter</a>
		<form class="d-flex">
			<button class="btn btn-outline-success" type="submit">Search</button>
			<input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">

		</form>
	</div>
	<div class="row mt-2"></div>

</div>

templates/materieltype/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edition d'un matériel type{% endblock %}

{% block body %}
  

    {{ include('materieltype/_form.html.twig', {'titre':'Edition d\'un  materiel type','button_label': 'Mettre à jour'}) }}

 
{% endblock %}

templates/materieltype/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Matériels de référence
{% endblock %}

{% block body %}

	<div class="row">
		<div class="col-md-11 mx-auto mb-5">
			<h1>
				<u>Matériels de référence</u>
			</h1>
		</div>
	</div>
	<div class="row" style="min-height:60vh">
		<div class="col-md-11 mx-auto">
			<table class="table">
				<thead>
					<tr>
						<th>Marque</th>
						<th>Modele</th>
						<th>Categorie</th>
						<th>actions</th>
					</tr>
				</thead>
				<tbody>
					{% for materieltype in materieltypes %}
						<tr>

							<td>{{ materieltype.marque }}</td>
							<td>{{ materieltype.modele }}</td>
							<td>{{ materieltype.categorie }}</td>
							<td>
								<a class="btn btn-sm btn-primary" href="{{ path('materieltype_show', {'id': materieltype.id}) }}">Détail</a>
								<a class="btn btn-sm btn-primary" href="{{ path('materieltype_edit', {'id': materieltype.id}) }}">Editer</a>
							</td>
						</tr>
					{% else %}
						<tr>
							<td colspan="8">no records found</td>
						</tr>
					{% endfor %}
				</tbody>
			</table>


		</div>
	</div>


	<div class="row mb-4">

		<div class=" col-md-4 offset-md-4" id="pagination_nav">

			{{ knp_pagination_render(materieltypes) }}


		</div>
		<div class="col-md-4 mx-auto text-center ">

			<a class="btn btn-sm btn-primary" href="{{ path('materieltype_new') }}">Nouveau matériel de référence</a>
		</div>
	</div>

{% endblock %}

templates/materieltype/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Materieltype{% endblock %}

{% block body %}
    

    {{ include('materieltype/_form.html.twig',{'titre':'Nouveau matériel type'}) }}

{% endblock %}

templates/materieltype/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Materieltype
{% endblock %}

{% block body %}

    {{ include('materieltype/_form.html.twig', {'titre':'Détail d\'un  materiel de référence','button_label': 'Mettre à jour'}) }}



{% endblock %}
{% block javascripts %}
<script>
$(document).ready(function(){
$('input').attr('readonly','true')
$('textarea').attr('readonly','true')

})
</script>

{% endblock %}